### ISSUE TITLE
Repackage okhttp

### ISSUE THREAD

**Issue by tomquist** [paulcbetts/ModernHttpClient#119]
In my android project I already included okhttp as a native binding. This causes duplicate addition of okhttp classes during build:

	/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Tool exited with code: 1. Output: 
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.lang.IllegalArgumentException: already added: Lcom/squareup/okhttp/Address;
		at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
		at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
		at com.android.dx.command.dexer.Main.processClass(Main.java:732)
		at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
		at com.android.dx.command.dexer.Main.access$300(Main.java:82)
		at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
		at com.android.dx.command.dexer.Main.run(Main.java:245)
		at com.android.dx.command.dexer.Main.main(Main.java:214)
		at com.android.dx.command.Main.main(Main.java:106)
	1 error; aborting

If you ship ModernHttpClient with an embedded version of okhttp you should probably repackage okhttp (e.g. using jarjar) so that it is possible to used it side-by-side with other dependencies. Another solution would be to extract okhttp into its own component.

**Comment by paulcbetts** [comment]
Can't you just remove your copy of OkHttp?

**Comment by paulcbetts** [comment]
Fixed? Maybe?

**Comment by NVentimiglia** [comment]
Ran into this. Have Project A referencing Project B and OkHttp. Project B is also referencing Project OkHttp. When I try to run Project A I get this error. The solution is to manually remove the OkHttp reference from the project. 

If you are using nuget (In my case, Project B was nuget). You must add Project B and OkHttp to your project and then manually remove the reference from project A to 'trick' it into working.
