### ISSUE TITLE
Xamarin.Android project fails to compile with Linker enabled after updating to 2.4 from Nuget

### ISSUE THREAD

**Issue by csunwold** [paulcbetts/ModernHttpClient#147]
I have a Xamarin.Android project that was running with ModernHttpClient 2.3 and worked perfectly. 

After updating to 2.4, if I build with Linking set to "SDK Assemblies Only" it fails to build with this error: 

Error	358	The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'System.IntPtr Android.Runtime.JNIEnv::StartCreateInstance(System.Type,System.String,Android.Runtime.JValue*)' (defined in 'OkHttp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'OkHttp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.IntPtr Android.Runtime.JNIEnv::StartCreateInstance(System.Type,System.String,Android.Runtime.JValue*)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1017	5	

If I set Linking to None it works fine.

**Comment by csunwold** [comment]
When I say if Linking is set to None it works fine, what I mean is that it builds, it doesn't actually make successful network requests.

**Comment by paulcbetts** [comment]
It was working for me, even on device. I suspect we've got different versions of Xamarin.Android maybe?

**Comment by csunwold** [comment]
You are right, Ill try upgrading to latest and try again.

**Comment by csunwold** [comment]
Sure enough upgrading to Xamarin.Android 5.1 worked. Perhaps its worth adding a note that ModernHttpClient 2.4 requires Xamarin.Android 5.1 or greater to build? I did notice in the release notes of 5.1 there are a number of breaking changes: https://forums.xamarin.com/discussion/37277/stable-release-xamarin-android-5-1-0-breaking-changes-new-features-and-bug-fixes

**Comment by Qonstrukt** [comment]
I've noticed the same. Unfortunately we can't upgrade to Xamarin Android 5.1 yet because it breaks using Android Support Library resources. Maybe it's possible to require a certain version in the nuget package? Using TargetFramework MonoAndroid51 in the nuspec might already be enough. (Wishful thinking: Maybe include a version compiled against 4.x :wink:)

**Comment by paulcbetts** [comment]
@Qonstrukt Just use `allowedVersions` to pin yourself at the previous ModernHttpClient version
