### ISSUE TITLE
Android app sometimes crashing with Java.Net.SocketException

### ISSUE THREAD

**Issue by coonmoo** [paulcbetts/ModernHttpClient#153]
Sometimes my android app using ModernHttpClient crashes.

I can't reproduce this problem, but it currently appears 1-2 times a day when using the app.
I'm on a Nexus 5 with Android 5.1.

Even if I try/catch the whole HttpClient.SendAsync with a general "Exception" handler, the app still completly crashes.

Do you have any idea?

This is the full stacktrace reported via hockeyapp:

```csharp
Java.Net.SocketException: Exception of type 'Java.Net.SocketException' was thrown.
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[OkHttp.Response].GetResult(.args:1337)
	at ModernHttpClient.NativeMessageHandler+<SendAsync>c__async0.MoveNext(.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult(.args:1337)
	at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext(.args:1337)
	at libcore.io.Posix.recvfromBytes(Native_Method.args:1337)
	at libcore.io.Posix.recvfrom(Posix.java:185.args:1337)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250.args:1337)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:553.args:1337)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485.args:1337)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37.args:1337)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237.args:1337)
	at okio.Okio$2.read(Okio.java:137.args:1337)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211.args:1337)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:295.args:1337)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289.args:1337)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196.args:1337)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190.args:1337)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80.args:1337)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830.args:1337)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95.args:1337)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823.args:1337)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684.args:1337)
	at com.squareup.okhttp.Call.getResponse(Call.java:272.args:1337)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228.args:1337)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199.args:1337)
	at com.squareup.okhttp.Call.access$100(Call.java:34.args:1337)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162.args:1337)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33.args:1337)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112.args:1337)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587.args:1337)
	at java.lang.Thread.run(Thread.java:818.args:1337)
```

**Comment by paulcbetts** [comment]
Hm, looks like we're not marshaling an exception properly

**Comment by coonmoo** [comment]
Same seems to happen with a "Java.Net.ConnectException".

Is there anything I can do to help you?

**Comment by paulcbetts** [comment]
Line numbers in this call stack would help :)

**Comment by dbeattie71** [comment]
I can reproduce this consistently.

**Comment by dbeattie71** [comment]
06-17 11:54:19.878 I/MonoDroid( 2428): UNHANDLED EXCEPTION:
06-17 11:54:19.880 I/MonoDroid( 2428): Java.Net.SocketException: Exception of type 'Java.Net.SocketException' was thrown.
06-17 11:54:19.880 I/MonoDroid( 2428): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
06-17 11:54:19.880 I/MonoDroid( 2428): at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
06-17 11:54:19.880 I/MonoDroid( 2428): at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
06-17 11:54:19.880 I/MonoDroid( 2428): at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
06-17 11:54:19.880 I/MonoDroid( 2428): at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
06-17 11:54:19.880 I/MonoDroid( 2428): at (wrapper dynamic-method) object.02df6a3d-5281-4f35-b14c-3ead871d4b7e (intptr,intptr) <IL 0x00011, 0x0001f>
06-17 11:54:19.880 I/MonoDroid( 2428):   --- End of managed exception stack trace ---
06-17 11:54:19.880 I/MonoDroid( 2428): java.net.SocketException: Socket closed
06-17 11:54:19.880 I/MonoDroid( 2428): 	at libcore.io.Posix.recvfromBytes(Native Method)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at libcore.io.Posix.recvfrom(Posix.java:185)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at okio.Okio$2.read(Okio.java:137)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:295)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.Call.getResponse(Call.java:272)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.Call.access$100(Call.java:34)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-17 11:54:19.880 I/MonoDroid( 2428): 	at java.lang.Thread.run(Thread.java:818)

**Comment by paulcbetts** [comment]
@dbeattie71 Can you get line numbers for the original call stack?

**Comment by coonmoo** [comment]
Sorry I couldn't provide you with the linenumbers.
But I have another one, which immediately crashes "randomly" my app if the Client is unable to connect to the host (even I catch the exception in my code).

```
InnerStackTraceJava.IO.IOExceptionfailed to connect to somehost.net (port 80): connect failed: EHOSTUNREACH (No route to host)
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[OkHttp.Response].GetResult () [0x00000] in <filename unknown>:0 
  at ModernHttpClient.NativeMessageHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
  --- End of managed exception stack trace ---
java.net.ConnectException: failed to connect to somehost.net  (port 80): connect failed: EHOSTUNREACH (No route to host)
	at libcore.io.IoBridge.connect(IoBridge.java:124)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
	at java.net.Socket.connect(Socket.java:882)
	at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:197)
	at com.squareup.okhttp.Connection.connect(Connection.java:156)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.access$100(Call.java:34)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: connect failed: EHOSTUNREACH (No route to host)
	at libcore.io.Posix.connect(Native Method)
	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	... 19 more
```

**Comment by coonmoo** [comment]
Still getting sometimes exceptions in my dashboard which aren't getting caught by my try/catch

```
System.AggregateExceptionSystem.AggregateException : Socket closed
Java.IO.IOException Socket Closed

 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[OkHttp.Response].GetResult () [0x00000] in <filename unknown>:0 
  at ModernHttpClient.NativeMessageHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
  --- End of managed exception stack trace ---
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:185)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at okio.Okio$2.read(Okio.java:137)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:295)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.access$100(Call.java:34)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by davidj-lynxlogic** [comment]
I was hoping to transition to ModernHttpClient to leverage its performance but also to address a problem we're seeing with the .net HttpClient. However, when testing we frequently ran into this issue, and having the app crash due to a network error is obviously a non-starter.

**Comment by SimonSimCity** [comment]
Hi, guys

Just to throw in the information I have:

We wrote an application and were having similar problems: some users reported that requests didn't finish - but just on some devices ... same as you guys here.

Now I got hands on one of those mobile-phones. It was a `Motorola Moto X Play` having `Android 5.1.1 Lolipop` installed. Always when I fired off a request, where I wanted to track the progress by using the method `RegisterForProgress()` an instance of `NativeMessageHandler` has, it crashed by exactly that exception. When I removed that method call, it works perfectly.

I wonder if it has something to do with this one ... https://stackoverflow.com/questions/30312571/socketexception-socket-closed-only-with-motorola-moto-g-2013 - maybe also a false positive.

If you need some further testing, I am willing to ask the guy, owning that phone, for a visit to do further testing.

**Comment by ncruces** [comment]
To prevent Xamarin.Android from crashing (and allow me to catch network errors) I needed to add this to my `Application` class:

```C#
[Application]
public class NetworkingApplication : Application
{
    public NetworkingApplication(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer) { }

    public override void OnCreate()
    {
        base.OnCreate();
        AndroidEnvironment.UnhandledExceptionRaiser += OnAndroidEnvironmentUnhandledException;
    }

    protected override void Dispose(bool disposing)
    {
        AndroidEnvironment.UnhandledExceptionRaiser -= OnAndroidEnvironmentUnhandledException;
        base.Dispose(disposing);
    }

    private void OnAndroidEnvironmentUnhandledException(object sender, RaiseThrowableEventArgs e)
    {
        // LOG
        if (e.Exception is Java.IO.IOException) e.Handled = true;
    }
}
```

Also see #195, which is related.

**Comment by deckertron9000** [comment]
@paulcbetts I managed to get some line numbers on the call stack (no line numbers on system .dlls for some reason) for the issue @dbeattie71 was reporting involving task cancellation. I'm attaching the file I collected. Let me know if I can help in any other way.
[ExceptionFromTaskCancellation.txt](https://github.com/paulcbetts/ModernHttpClient/files/64613/ExceptionFromTaskCancellation.txt)

**Comment by Krumelur** [comment]
This is a stack trace from the Galaxy S5 Emulator (XAP). Similar exception. Reproducible every time I cancel a download.

Error: download from 'http://www........com/video/app/9T4G-nd_0b3H_IR8eHfWaA.mp4' failed.; Java.Net.SocketException: recvfrom failed: EBADF (Bad file number) ---> Android.Systems.ErrnoException: recvfrom failed: EBADF (Bad file number)
03-18 15:35:31.238 I/BABY    ( 2127): 
03-18 15:35:31.238 I/BABY    ( 2127):   --- End of managed exception stack trace ---
03-18 15:35:31.238 I/BABY    ( 2127): android.system.ErrnoException: recvfrom failed: EBADF (Bad file number)
03-18 15:35:31.238 I/BABY    ( 2127): 	at libcore.io.Posix.recvfromBytes(Native Method)
03-18 15:35:31.238 I/BABY    ( 2127): 	at libcore.io.Posix.recvfrom(Posix.java:185)
03-18 15:35:31.238 I/BABY    ( 2127): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
03-18 15:35:31.238 I/BABY    ( 2127): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
03-18 15:35:31.238 I/BABY    ( 2127): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
03-18 15:35:31.238 I/BABY    ( 2127): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
03-18 15:35:31.238 I/BABY    ( 2127): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
03-18 15:35:31.238 I/BABY    ( 2127): 	at okio.Okio$2.read(Okio.java:137)
03-18 15:35:31.238 I/BABY    ( 2127): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
03-18 15:35:31.238 I/BABY    ( 2127): 	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
03-18 15:35:31.238 I/BABY    ( 2127): 	at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:390)
03-18 15:35:31.238 I/BABY    ( 2127): 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:338)
03-18 15:35:31.238 I/BABY    ( 2127): 
03-18 15:35:31.238 I/BABY    ( 2127):   --- End of inner exception stack trace ---
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
03-18 15:35:31.238 I/BABY    ( 2127):   at Android.Runtime.JNIEnv.CallIntMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00064] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:404 
03-18 15:35:31.238 I/BABY    ( 2127):   at Java.IO.InputStream.Read (System.Byte[] buffer, Int32 byteOffset, Int32 byteCount) [0x00089] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.IO.InputStream.cs:302 
03-18 15:35:31.238 I/BABY    ( 2127):   at Android.Runtime.InputStreamInvoker.Read (System.Byte[] buffer, Int32 offset, Int32 count) [0x00000] in /Users/builder/data/lanes/2970/46c3f7e0/source/monodroid/src/Mono.Android/src/Runtime/InputStreamInvoker.cs:30 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.IO.Stream.<BeginReadInternal>m__2 (System.Object ) [0x0000b] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/io/stream.cs:347 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x00031] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:692 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
03-18 15:35:31.238 I/BABY    ( 2127): --- End of stack trace from previous location where exception was thrown ---
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:372 
03-18 15:35:31.238 I/BABY    ( 2127):   at System.IO.Stream.EndRead (IAsyncResult asyncResult) [0x00060] in /Users/builder/data/lanes/2970/46c3f7e0/source/mono/external/referenc
Thread finished: <Thread Pool> #5

**Comment by adrianknight89** [comment]
Running into this issue, but looks like this library is no longer in active development.
