### ISSUE TITLE
Build error with Picasso Library

### ISSUE THREAD

**Issue by SagarPanwala** [paulcbetts/ModernHttpClient#181]
I want to use this library, but I am unable to add that in my Xamarin Project. I want to use it with combination of Picasso package. But unable to use it. Please help me I stuck on this issue from past 2 days.

**Comment by Cheesebaron** [comment]
If you get a build error, maybe you should share that exact error?

**Comment by JeroenMols** [comment]
I believe 'm getting the same error: a conflict between OkHttp in ModernHttpClient and in Picasso

My project setup is the following:
- MyApp-Android
    - Reference to Picasso (2.5.2.0, Square.Picasso)
- MyApp-iOS
- MySharedLibrary
    - Reference to ModerHttpClient (2.4.2.0, ModernHttpClient)

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Tool exited with code: 1. Output: 
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/squareup/okhttp/Address;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:214)
	at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lokio/AsyncTimeout$1;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:214)
	at com.android.dx.command.Main.main(Main.java:106)
2 errors; aborting

Let me know if you need more info.

**Comment by lukax** [comment]
experiencing same problems here

**Comment by Cheesebaron** [comment]
OK, so both Picasso and ModernHttpClient should pull in OkHttp through a nuget, rather than both providing their own version of it.

For ModenHttpClient that is the case in new versions since August 24. For Picasso I have no idea. Talk to the author of Picasso to tell him to use the OkHttp nuget as well.

**Comment by JeroenMols** [comment]
Created a pull request for Picasso which should also solve this issue on Picasso side.

**Comment by SagarPanwala** [comment]
Hey What do you mean by create a Pull Request? I just downloaded the binding from https://github.com/jacksierkstra/Picasso
But it is still not working. If this is not the way to download , please help me to use that.

**Comment by SagarPanwala** [comment]
Hey After downloading the latest binding. I'm facing the new issue. Picasso is not loading images many times. I can't able to figure out at what time it fails. It throws error like 

Java.Lang.NoClassDefFoundError was thrown

**Comment by SharpMobileCode** [comment]
Is this included in the latest release on Nuget?  If not, any timeframe for that?

**Comment by Qonstrukt** [comment]
Would like to know the same, things have been awfully silent around ModernHttpClient lately.

**Comment by Cheesebaron** [comment]
Looking at the tree for [2.4.2](https://github.com/paulcbetts/ModernHttpClient/tree/2.4.2) and looking in the nuspec, you will see that the hard coded OkHttp dependency is still there. Hence it has not yet been released.

**Comment by Jagadeesh-Govindaraj** [comment]
https://github.com/JoeMayo/LinqToTwitter/issues/59
https://github.com/jaymedavis/stripe.net/issues/500

please release new version i think this issue is fixed right now according this [PR](https://github.com/paulcbetts/ModernHttpClient/pull/177)

**Comment by jzeferino** [comment]
@JeroenMols Did the Picasso PR was release yet?

**Comment by JeroenMols** [comment]
No idea, sorry

**Comment by jzeferino** [comment]
Can you link me the PR? I want to remind them of that! @JeroenMols

**Comment by JeroenMols** [comment]
https://github.com/jacksierkstra/Picasso/pull/7

it was right above my comment btw :)

**Comment by jzeferino** [comment]
Thanks my friend. I've already remind the guys from square to fix it here: https://github.com/mattleibow/square-bindings/issues/2

**Comment by samofwise** [comment]
@paulcbetts Thanks for making the changes so that ModernHttpClient could use OkHttp on nuget (seen in this [commit](https://github.com/paulcbetts/ModernHttpClient/commit/b797738ee2ec953dc56919dc1ef5d808ea24b784)).
But could you please release this new version on nuget??
