### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by aerlian** [paulcbetts/ModernHttpClient#182]
Hi Paul,

I'm experiencing a problem when invoking HttpClient.PostAsync(). I've tried the call from 2 Android devices (Nexus 10 KitKat & Samsung Galaxy Tablet) and in both cases I get an exception with the call stack below [1].

At first I thought it was perhaps a problem with the server certificate not being installed correctly, but I have since eliminated that by checking it with the CA via their online tool (https://www.digicert.com/help/) and the final statement on the report generated is: "Congratulations! This certificate is correctly installed."

I also checked the security settings on the Android device to make sure the root certificate for DigiCert is installed and has the checkbox tick, which it is on both accounts (the cert is found under the system certificates)

Do you have any suggestions for what else I might check?

Steve

[1]
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:430)
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:242)
	at com.squareup.okhttp.Connection.connect(Connection.java:159)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.access$100(Call.java:34)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:663)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:426)
	... 16 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by chamamo** [comment]
I have the same issue, any idea?

**Comment by deserthero** [comment]
check that http://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection

**Comment by asura1234** [comment]
I have the same issue. I think the post above applies to android native development. I'm not sure how to do the same in Xamarin.

**Comment by asadwaheed1** [comment]
I also have the same problem.

**Comment by paradisehuman** [comment]
I also have same problem

**Comment by Momomotus** [comment]
same problem here

**Comment by gustblima** [comment]
+1

**Comment by 893573771** [comment]
me too

**Comment by antferr** [comment]
resolution for xamarin?

**Comment by arkilis** [comment]
Same issue with native dev

**Comment by amintabar** [comment]
How to resolve this problem?

**Comment by Cheesebaron** [comment]
Resolve it by not using ModernHttpClient

**Comment by ozanurkn** [comment]
same issue can anybody help us ?

**Comment by remyasics** [comment]
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found #182

**Comment by alexrainman** [comment]
You can use modernhttpclient-updated https://github.com/alexrainman/ModernHttpClient :)
